# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hail < Formula
  desc "Universal communication platform for AI agents (CLI)"
  homepage "https://hail.so"
  version "0.1.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hail-hq/hail/releases/download/v0.1.0/hail_0.1.0_darwin_amd64.tar.gz"
      sha256 "7500b6985374006363c9946d213e98a44a1c2f080490dedaf97d8fe6218009a7"

      define_method(:install) do
        bin.install "hail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hail-hq/hail/releases/download/v0.1.0/hail_0.1.0_darwin_arm64.tar.gz"
      sha256 "37c9057a8114d9771783fa8ef65b6961adac52b1e50e066577e3bba20c2a3798"

      define_method(:install) do
        bin.install "hail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hail-hq/hail/releases/download/v0.1.0/hail_0.1.0_linux_amd64.tar.gz"
      sha256 "a84769fd7736eb52ba4e111fb03032c1f2fe2c93987a7644cb3ff41f35017609"
      define_method(:install) do
        bin.install "hail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hail-hq/hail/releases/download/v0.1.0/hail_0.1.0_linux_arm64.tar.gz"
      sha256 "4aa717f98c8a4c8529d32b8f0aa3dd3524ec8e6de5e0a981337afa597f871045"
      define_method(:install) do
        bin.install "hail"
      end
    end
  end

  test do
    system "#{bin}/hail", "--version"
  end
end
