# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hail < Formula
  desc "Universal communication platform for AI agents (CLI)"
  homepage "https://hail.so"
  version "0.15.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hail-hq/hail/releases/download/v0.15.0/hail_0.15.0_darwin_amd64.tar.gz"
      sha256 "6feddc4be2433eea936ae4ba0c62707d2cb18438cdc8eca4dafc26dec310b6a4"

      define_method(:install) do
        bin.install "hail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hail-hq/hail/releases/download/v0.15.0/hail_0.15.0_darwin_arm64.tar.gz"
      sha256 "bf76649ea865f38c498045408bd9c574d806e60a53770157e5bdfd813b5f4d7d"

      define_method(:install) do
        bin.install "hail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hail-hq/hail/releases/download/v0.15.0/hail_0.15.0_linux_amd64.tar.gz"
      sha256 "67d36c4c56bf211ea662e06d1e86243baae1c692190e3d70417029485b3675e6"
      define_method(:install) do
        bin.install "hail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hail-hq/hail/releases/download/v0.15.0/hail_0.15.0_linux_arm64.tar.gz"
      sha256 "fda17a1e62dd7f9e05471092668fca1ddde4fbdb7346f5c501220e32b0da537e"
      define_method(:install) do
        bin.install "hail"
      end
    end
  end

  test do
    system "#{bin}/hail", "--version"
  end
end
